name: Build and Publish

on:
  push:
    paths:
      - '.github/CHANGELOG.md'
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.0
        with:
          node-version: '12'
          check-latest: true

      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.0-8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/squishy
          destination_dir: latest
          full_commit_message: ${{ github.event.head_commit.message }}